### ISSUE TITLE
Scan working directories and register all non-references scripts to a dummy block

### ISSUE THREAD

**Issue by mriceberg** [mriceberg/DBUpdate#9]

**Comment by mriceberg** [comment]
Controlled by a flag.

**Comment by Ethan0079** [comment]
1. Add argument to execute (--scan) with name of the xml file in which to add the new block
2. If file exist create a new block definition with the sql file in
3. If not create a new one with the dummy block definition and add script
4. Do not include the dummyBlock in blockToExecute
5. Add argument --scanOnly to list the sqlFile ()

**Comment by Ethan0079** [comment]
6. Create new class scan....
